name: Sync fork from upstream

on:
  schedule:
    - cron: '*/5 * * * *'  # 5분마다 체크
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/Likelion-Yonsei-14th/unity-yonsei-client.git
          git fetch upstream main

      - name: Sync main
        run: |
          git checkout main
          git reset --hard upstream/main
          git push origin main --force